services:
  # app service
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    ports:
     - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      #MYSQL_PASSWORD_FILE: run/secrets/db_password
    # secrets:
    #   - db_password
    depends_on:
      - keycloak
      - mysql
  # mysql service
  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    # secrets:
    #   - db_root_password
  # keycloak service
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    ports:
      - 8080:8080
    volumes:
      - todo-keycloak-data:/opt/keycloak/data/
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      #- KEYCLOAK_ADMIN_PASSWORD_FILE=run/secrets/keycloak_admin_password
    # secrets:
    #   - keycloak_admin_password
# volume mapping
volumes:
  todo-mysql-data:
  todo-keycloak-data:
# secrets
# secrets:
#   db_password:
#     file: ./db_password.txt
#   db_root_password:
#     file: ./db_root_password.txt
#   keycloak_admin_password:
#     file: ./keycloak_admin_password.txt