services:
  # app backend service
  backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend/:/app
      - todo-backend-data:/app/node_modules
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - .env
    depends_on:
      keycloak:
        condition: service_healthy
      mysql:
        condition: service_started
  # app frontend service
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - todo-frontend-data:/app/node_modules
    depends_on:
      - keycloak
      - mysql
      - backend
    ports:
      - 4000:8080
  # database service
  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    env_file:
      - .env
  # keycloak service
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start-dev --import-realm
    ports:
      - 9000:8080
    volumes:
      # storing keycloak data
      - todo-keycloak-data:/opt/keycloak/data/
      # for importing keycloak realm
      - ./keycloak/:/opt/keycloak/data/import/
    env_file:
      - .env
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/localhost/8080'
      interval: 1s
      timeout: 10s
      retries: 5
      start_period: 60s
# volume mapping
volumes:
  todo-mysql-data:
  todo-keycloak-data:
  todo-frontend-data:
  todo-backend-data:
