services:
  # app service
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    ports:
     - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
  # mysql service
  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
  # keycloak service
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    command: start-dev
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - todo-keycloak-data:/opt/keycloak/data/
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
# volume mapping
volumes:
  todo-mysql-data:
  todo-keycloak-data: