services:
  # app backend service
  backend:
    # build: backend
    image: node:21-alpine
    command: sh -c "npm install && npm run dev"
    ports:
     - 3000:3000
    working_dir: /app
    volumes:
      - ./backend/:/app
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - .env
    depends_on:
      - keycloak
      - mysql
  # app frontend service
  frontend:
    build: frontend/frontend
    volumes:
      - ./frontend/frontend/src/:/app/src
      - ./frontend/frontend/public/:/app/public
      - type: bind
        source: ./frontend/frontend/package.json
        target: /app/package.json
    depends_on:
      - keycloak
      - mysql
      - backend
    ports:
      - 4000:8080
  # mysql service
  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    env_file:
      - .env
  # keycloak service
  keycloak:
    image: quay.io/keycloak/keycloak:23.06
    command: start-dev --import-realm
    ports:
      - 9000:8080
    volumes:
      # storing keycloak data
      - todo-keycloak-data:/opt/keycloak/data/
      # for importing keycloak realm
      - ./backend/keycloak:/opt/keycloak/data/import/
    env_file:
      - .env
# volume mapping
volumes:
  todo-mysql-data:
  todo-keycloak-data: