services:
  # app backend service
  backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      # better dev experience
      - ./backend/:/app
      # to prevent dependencies errors
      - backend-node_modules:/app/node_modules
    # linux doesn't know what is host.docker.internal
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ./backend/backend.env
    depends_on:
      keycloak:
        condition: service_healthy
  # app frontend service
  frontend:
    build: ./frontend
    ports:
      - 4000:8080
    volumes:
      # better dev experience
      - ./frontend:/app
      # to prevent dependencies errors
      - frontend-node_modules:/app/node_modules
    # linux doesn't know what is host.docker.internal
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ./frontend/frontend.env
    depends_on:
      - keycloak
      - backend
  # keycloak service
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command: start-dev --import-realm
    # build: ./keycloak
    ports:
      - 9000:8080
    volumes:
      # storing keycloak data
      - todo-keycloak-data:/opt/keycloak/data/
      # for importing keycloak realm
      - ./keycloak/:/opt/keycloak/data/import/
      # for importing custom keycloak theme
      - ./keycloak/themes/custom/:/opt/keycloak/themes/custom
      # disable theme cache
      - ./keycloak/themes/disable-theme-cache.cli/:/opt/jboss/startup-scripts/disable-theme-cache.cli
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/localhost/8080'
      interval: 1s
      timeout: 10s
      retries: 5
      start_period: 60s
    env_file:
      - ./keycloak/keycloak.env
# volume mapping
volumes:
  todo-keycloak-data:
  frontend-node_modules:
  backend-node_modules:
