services:
  # app backend service
  backend:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    ports:
     - 3000:3000
    working_dir: /app
    volumes:
      - ./backend/:/app
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - .env
    depends_on:
      - keycloak
      - mysql
  # app frontend service
  frontend:
    image: nginx:latest
    command: 
    ports:
      - 4000:80
    volumes:
      - ./frontend/:/app
    depends_on:
      - keycloak
      - mysql
      - backend
  # mysql service
  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    env_file:
      - .env
  # keycloak service
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    ports:
      - 9000:8080
    volumes:
      - todo-keycloak-data:/opt/keycloak/data/
      - ./backend/keycloak:/opt/keycloak/data/import/
    env_file:
      - .env
# volume mapping
volumes:
  todo-mysql-data:
  todo-keycloak-data: